# Generated by Django 2.2.3 on 2019-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20190622_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='seen',
            new_name='seen_by_receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='seen_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
