# Generated by Django 2.2.3 on 2019-07-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_auto_20190705_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='seen_by_sender',
            new_name='seen',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by_receiver',
        ),
    ]
