# Generated by Django 2.2.2 on 2019-06-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contack_no',
            field=models.CharField(max_length=15),
        ),
    ]
