# Generated by Django 2.2.2 on 2019-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0003_online_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_user',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
