# Generated by Django 2.2.2 on 2019-06-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0004_auto_20190623_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_user',
            name='last_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
