# Generated by Django 2.2.2 on 2019-06-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0005_auto_20190623_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online_user',
            name='last_seen',
            field=models.DateTimeField(),
        ),
    ]
