# Generated by Django 2.2.2 on 2019-06-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0007_auto_20190624_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
