# Generated by Django 2.2.2 on 2019-06-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0008_auto_20190624_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='is_turned_off',
            field=models.BooleanField(default=False),
        ),
    ]
