# Generated by Django 2.2.2 on 2019-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0009_online_is_turned_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='is_turned_off',
            field=models.BooleanField(blank=True),
        ),
    ]
