# Generated by Django 2.2.3 on 2019-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0010_auto_20190624_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='is_turned_off',
            field=models.BooleanField(default=0),
        ),
    ]
